# Generated by Django 5.1.7 on 2025-06-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0012_remove_equipmentmodel_model_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this token expires (null = permanent)', null=True),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='Whether this is a temporary token that should be auto-cleaned'),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='session_info',
            field=models.JSONField(blank=True, default=dict, help_text='Additional session information for temporary tokens'),
        ),
    ]
