# Generated by Django 5.1.7 on 2025-06-10 19:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0013_apitoken_expires_at_apitoken_is_temporary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labequipmentpage',
            name='alt_text_suggestions',
            field=models.JSONField(blank=True, default=list, help_text='SEO-optimized alt text suggestions for equipment images'),
        ),
        migrations.AddField(
            model_name='labequipmentpage',
            name='applications',
            field=models.JSONField(blank=True, default=list, help_text='Lab applications and use cases for this equipment'),
        ),
        migrations.AddField(
            model_name='labequipmentpage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Compelling meta description with key features (150-160 characters)', max_length=160),
        ),
        migrations.AddField(
            model_name='labequipmentpage',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Comma-separated list of primary, secondary, technical, specification keywords'),
        ),
        migrations.AddField(
            model_name='labequipmentpage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO-optimized title tag (50-60 characters). Leave blank to auto-generate from title.', max_length=60),
        ),
        migrations.AddField(
            model_name='labequipmentpage',
            name='page_content_sections',
            field=models.JSONField(blank=True, default=dict, help_text='Organized content sections (overview, specifications, applications, models)'),
        ),
        migrations.AddField(
            model_name='labequipmentpage',
            name='related_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Secondary search terms (5-10 terms: applications, specifications, features)'),
        ),
        migrations.AddField(
            model_name='labequipmentpage',
            name='seo_content',
            field=wagtail.fields.RichTextField(blank=True, help_text='Additional SEO-rich content incorporating specifications and features'),
        ),
        migrations.AddField(
            model_name='labequipmentpage',
            name='structured_data',
            field=models.JSONField(blank=True, default=dict, help_text='Schema.org structured data for rich snippets (JSON-LD format)'),
        ),
        migrations.AddField(
            model_name='labequipmentpage',
            name='target_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Primary search keywords (3-5 terms: equipment type, brand, model)'),
        ),
        migrations.AddField(
            model_name='labequipmentpage',
            name='technical_keywords',
            field=models.JSONField(blank=True, default=list, help_text='Technical terms and specifications for expert searches'),
        ),
        migrations.AddField(
            model_name='labequipmentpage',
            name='technical_specifications',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed technical specifications in structured format'),
        ),
    ]
