# Generated by Django 5.1.7 on 2025-06-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_extractor', '0002_fieldselectionsession_sitefieldselector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldselectionsession',
            name='total_fields',
            field=models.IntegerField(default=11, help_text='Total LabEquipmentPage fields'),
        ),
    ]
