# Generated by Django 5.1.7 on 2025-06-08 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_extractor', '0005_contentextractionrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_equipment_field', models.CharField(choices=[('title', 'Title'), ('short_description', 'Short Description'), ('full_description', 'Full Description'), ('models', 'Models'), ('features', 'Features'), ('accessories', 'Accessories'), ('categorized_tags', 'Categorized Tags'), ('gallery_images', 'Gallery Images'), ('spec_groups', 'Specification Groups'), ('source_url', 'Source URL'), ('specification_confidence', 'Specification Confidence'), ('needs_review', 'Needs Review'), ('data_completeness', 'Data Completeness'), ('source_type', 'Source Type')], help_text='LabEquipmentPage model field this configuration targets', max_length=100)),
                ('xpath_selectors', models.JSONField(blank=True, default=list, help_text='List of XPath strings to try for extracting this field content')),
                ('comment', models.TextField(blank=True, help_text='Context comment for AI processing - explains what this field should contain')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this field configuration is active for extraction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this field configuration', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field Configuration',
                'verbose_name_plural': 'Field Configurations',
                'ordering': ['site_config__site_name', 'lab_equipment_field'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_domain', models.CharField(help_text="Site domain (e.g., 'airscience.com', 'example-lab-supplier.com')", max_length=255, unique=True)),
                ('site_name', models.CharField(help_text='Human-readable site name for identification', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this site configuration is active for extraction')),
                ('notes', models.TextField(blank=True, help_text='Notes about this site configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this configuration', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
                'ordering': ['site_name', 'site_domain'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='aipreparationrecord',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='aipreparationrecord',
            name='parent_record',
        ),
        migrations.AlterUniqueTogether(
            name='analyzedpage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='analyzedpage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='contentselector',
            name='pages_matched',
        ),
        migrations.DeleteModel(
            name='ContentExtractionRecord',
        ),
        migrations.AlterUniqueTogether(
            name='contentselector',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contentselector',
            name='project',
        ),
        migrations.RemoveField(
            model_name='extractionproject',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='selectionsession',
            name='project',
        ),
        migrations.DeleteModel(
            name='FieldSelectionSession',
        ),
        migrations.AlterUniqueTogether(
            name='selectortestresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='selectortestresult',
            name='selector',
        ),
        migrations.AlterUniqueTogether(
            name='sitefieldselector',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sitefieldselector',
            name='created_by',
        ),
        migrations.CreateModel(
            name='FieldConfigurationSnippet',
            fields=[
            ],
            options={
                'verbose_name': 'Field Configuration',
                'verbose_name_plural': 'Field Configurations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content_extractor.fieldconfiguration',),
        ),
        migrations.AddField(
            model_name='fieldconfiguration',
            name='site_config',
            field=models.ForeignKey(help_text='Site configuration this field belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='field_configs', to='content_extractor.siteconfiguration'),
        ),
        migrations.CreateModel(
            name='SiteConfigurationSnippet',
            fields=[
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configurations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content_extractor.siteconfiguration',),
        ),
        migrations.DeleteModel(
            name='AIPreparationRecord',
        ),
        migrations.DeleteModel(
            name='AnalyzedPage',
        ),
        migrations.DeleteModel(
            name='ContentSelector',
        ),
        migrations.DeleteModel(
            name='ExtractionProject',
        ),
        migrations.DeleteModel(
            name='SelectionSession',
        ),
        migrations.DeleteModel(
            name='SelectorTestResult',
        ),
        migrations.DeleteModel(
            name='SiteFieldSelector',
        ),
        migrations.AlterUniqueTogether(
            name='fieldconfiguration',
            unique_together={('site_config', 'lab_equipment_field')},
        ),
    ]
