# Generated by Django 5.1.7 on 2025-06-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_extractor', '0006_create_site_configuration_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldConfigurationSnippet',
        ),
        migrations.DeleteModel(
            name='SiteConfigurationSnippet',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='test_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of test URLs to verify selectors work across different pages of this domain'),
        ),
    ]
