# Generated by Django 5.1.7 on 2025-06-09 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_extractor', '0007_delete_fieldconfigurationsnippet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='test_urls',
        ),
        migrations.CreateModel(
            name='SiteURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Full URL to be processed for content extraction', max_length=500)),
                ('page_title', models.CharField(blank=True, help_text='Auto-populated page title from scraped content', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', help_text='Whether this URL is active for processing', max_length=20)),
                ('last_processed', models.DateTimeField(blank=True, help_text='Timestamp of last successful processing', null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Current processing status for AI JSON generation', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes about this URL or processing results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who added this URL', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site_config', models.ForeignKey(help_text='Site configuration this URL belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='content_extractor.siteconfiguration')),
            ],
            options={
                'verbose_name': 'Site URL',
                'verbose_name_plural': 'Site URLs',
                'ordering': ['site_config__site_name', 'url'],
                'unique_together': {('site_config', 'url')},
            },
        ),
        migrations.CreateModel(
            name='AIJSONRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField(help_text='Complete AI-ready JSON combining scraped content and XPath configurations')),
                ('generation_timestamp', models.DateTimeField(auto_now_add=True, help_text='When this JSON was generated')),
                ('content_hash', models.CharField(help_text='SHA256 hash of the scraped content for change detection', max_length=64)),
                ('processing_duration', models.DurationField(blank=True, help_text='Time taken to generate this JSON', null=True)),
                ('is_current', models.BooleanField(default=True, help_text='Whether this is the most recent JSON for this URL')),
                ('site_url', models.ForeignKey(help_text='Site URL this JSON was generated from', on_delete=django.db.models.deletion.CASCADE, related_name='ai_json_records', to='content_extractor.siteurl')),
            ],
            options={
                'verbose_name': 'AI JSON Record',
                'verbose_name_plural': 'AI JSON Records',
                'ordering': ['-generation_timestamp'],
            },
        ),
    ]
