# Generated by Django 5.1.7 on 2025-06-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_extractor', '0008_remove_siteconfiguration_test_urls_siteurl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldconfiguration',
            name='lab_equipment_field',
            field=models.CharField(choices=[('title', 'Title'), ('short_description', 'Short Description'), ('full_description', 'Full Description'), ('models', 'Models'), ('model_name', 'Model Name'), ('features', 'Features'), ('accessories', 'Accessories'), ('categorized_tags', 'Categorized Tags'), ('gallery_images', 'Gallery Images'), ('spec_groups', 'Specification Groups'), ('source_url', 'Source URL'), ('specification_confidence', 'Specification Confidence'), ('needs_review', 'Needs Review'), ('data_completeness', 'Data Completeness'), ('source_type', 'Source Type')], help_text='LabEquipmentPage model field this configuration targets', max_length=100),
        ),
    ]
