# Generated by Django 5.1.7 on 2025-06-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_extractor', '0009_add_model_name_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldconfiguration',
            name='lab_equipment_field',
            field=models.CharField(choices=[('title', 'Title'), ('short_description', 'Short Description'), ('full_description', 'Full Description'), ('models', 'Models'), ('model_name', 'Model Name'), ('name', 'Name (Generic)'), ('features', 'Features'), ('accessories', 'Accessories'), ('categorized_tags', 'Categorized Tags'), ('gallery_images', 'Gallery Images'), ('spec_groups', 'Specification Groups'), ('specification_group_names', 'Specification Group Names'), ('source_url', 'Source URL'), ('specification_confidence', 'Specification Confidence'), ('needs_review', 'Needs Review'), ('data_completeness', 'Data Completeness'), ('source_type', 'Source Type'), ('meta_title', 'Meta Title'), ('meta_description', 'Meta Description'), ('meta_keywords', 'Meta Keywords'), ('seo_content', 'SEO Content'), ('target_keywords', 'Target Keywords'), ('related_keywords', 'Related Keywords'), ('technical_keywords', 'Technical Keywords'), ('structured_data', 'Structured Data'), ('alt_text_suggestions', 'Alt Text Suggestions'), ('page_content_sections', 'Page Content Sections'), ('applications', 'Applications'), ('slug', 'URL Slug')], help_text='LabEquipmentPage model field this configuration targets', max_length=100),
        ),
    ]
