# Generated by Django 5.1.7 on 2025-06-15 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_extractor', '0010_add_specification_group_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInferenceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(help_text='Human-readable name for the batch inference job', max_length=255)),
                ('job_arn', models.CharField(help_text='AWS Bedrock batch inference job ARN', max_length=512, unique=True)),
                ('job_id', models.CharField(help_text='AWS Bedrock batch inference job ID (extracted from ARN)', max_length=255)),
                ('model_id', models.CharField(help_text='AWS Bedrock model ID used for inference', max_length=255)),
                ('prompt_arn', models.CharField(help_text='AWS Bedrock prompt ARN used for inference', max_length=512)),
                ('input_s3_uri', models.CharField(help_text='S3 URI of the input JSONL file', max_length=1024)),
                ('output_s3_uri', models.CharField(help_text='S3 URI where results will be stored', max_length=1024)),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Stopping', 'Stopping'), ('Stopped', 'Stopped')], default='Submitted', help_text='Current status of the batch inference job', max_length=20)),
                ('record_count', models.IntegerField(blank=True, help_text='Number of records submitted for processing', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When the job was submitted to Bedrock')),
                ('started_at', models.DateTimeField(blank=True, help_text='When the job started processing', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the job completed (success or failure)', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for job failure, if applicable')),
                ('notes', models.TextField(blank=True, help_text='Notes about this batch inference job')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who submitted this batch job', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site_config', models.ForeignKey(help_text='Site configuration this batch job belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='batch_inference_jobs', to='content_extractor.siteconfiguration')),
            ],
            options={
                'verbose_name': 'Batch Inference Job',
                'verbose_name_plural': 'Batch Inference Jobs',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
